services:
  templates_state:
    container_name: app-hasura-db
    build:
      context: ${SRC}/templates/app-hasura-db/app
      dockerfile: ${SRC}/templates/app-hasura-db/docker/Dockerfile
    restart: always
    env_file:
      - ${SRC}/templates/app-hasura-db/.env.local
      - ${SRC}/templates/app-hasura-db/.env.base
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_SERVER_PORT: ${PORT}
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'

    ports:
      - ${PORT}:${PORT}
