services:
  app:
    container_name: ${APP}
    build:
      context: ${SRC}/${PROJECT}/${APP}/app
      dockerfile: ${SRC}/${PROJECT}/${APP}/docker/Dockerfile
    restart: always
    env_file:
      - ${SRC}/${PROJECT}/${APP}/.env.base
      - ${SRC}/${PROJECT}/${APP}/.env.local
    environment:
      APP: ${APP}
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_SERVER_PORT: ${PORT}
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
    ports:
      - ${PORT}:${PORT}
