services:
  app:
    container_name: ${APP}
    build:
      context: ${SRC}/${PROJECT}/${APP}/app
      dockerfile: ${SRC}/${PROJECT}/${APP}/docker/Dockerfile
      args:
        LOCAL: 'true'
    env_file:
      - ${SRC}/${PROJECT}/${APP}/.env.base
      - ${SRC}/${PROJECT}/${APP}/.env.local
    ports:
      - ${PORT}:${PORT}
    environment:
      APP: ${APP}
      NEXTAUTH_URL: ${NEXTAUTH_URL-http://localhost:${PORT}}
      LOCALHOST_SRC: ${LOCALHOST_SRC}

    volumes:
      - ${LOCALHOST_SRC}/${PROJECT}/${APP}/app:/usr/app/main
    command: ['npm', 'run', 'dev']
