services:
  ui:
    container_name: ${APP}
    build:
      context: ${SRC}/${PROJECT}/${APP}/app
      dockerfile: ${SRC}/${PROJECT}/${APP}/docker/Dockerfile
      args:
        LOCAL: "true"
    env_file:
      - ${SRC}/${PROJECT}/${APP}/.env.base
      - ${SRC}/${PROJECT}/${APP}/.env.local
    ports:
      - ${PORT}:${PORT}
    environment:
      APP: ${APP}
      LOCALHOST_SRC: ${LOCALHOST_SRC}
    volumes:
      - ${LOCALHOST_SRC}/${PROJECT}/${APP}/app:/usr/app/main
    command: ["npm", "run", "dev"]
